# Enable H2 database console in browser
spring.h2.console.enabled=true
# Console URL: http://localhost:8080/h2-console
spring.h2.console.path=/h2-console

# Database Settings (In-memory)
spring.datasource.url=jdbc:h2:mem:catalogdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL commands in console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
